# This is a basic workflow to help you get started with Actions
name: git comment
on:
  issues:
  push:
    types: [open_issues]

jobs:
  comment: 
    runs-on: ‘issues’
    steps:
      - name: Add git comment
        uses: Marta83/funny-comment-action@v2.1
        id: FunnyComment
        with: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIPHY_TOKEN: ${{ secrets.GIPHY_TOKEN }}    
          comment_type: 'gif' 
